export const EGYPT_GOVS = {
  'منزلة': [
    { name: 'منزلة', price: 65 }
  ],
  'القاهرة': [
    { name: 'مدينة نصر', price: 75 },
    { name: 'مصر الجديدة', price: 75 },
    { name: 'شبرا', price: 75 },
    { name: 'الزيتون', price: 75 },
    { name: 'عين شمس', price: 75 },
    { name: 'المطرية', price: 75 },
    { name: 'الساحل', price: 75 },
    { name: 'الوايلي', price: 75 },
    { name: 'الزمالك', price: 75 },
    { name: 'وسط البلد', price: 75 },
    { name: 'العباسية', price: 75 },
    { name: 'مصر القديمة', price: 75 },
    { name: 'السيدة زينب', price: 75 },
    { name: 'الخليفة', price: 75 },
    { name: 'البساتين', price: 75 },
    { name: 'دار السلام', price: 75 },
    { name: 'طرة', price: 75 },
    { name: 'المعصرة', price: 75 },
    { name: 'التبين', price: 75 },
    { name: 'منشأة ناصر', price: 75 },
    { name: 'الزهراء', price: 75 },
    { name: 'عزبة النخل', price: 75 }
  ],
  'الجيزة': [
    { name: 'العجوزة', price: 75 },
    { name: 'الدقي', price: 75 },
    { name: 'الهرم', price: 75 },
    { name: 'إمبابة', price: 75 },
    { name: 'بولاق الدكرور', price: 75 },
    { name: 'الوراق', price: 75 },
    { name: 'دهشور', price: 75 },
    { name: 'كفر طهرمس', price: 75 }
  ],
  'التجمع والقطامية والخصوص وبدرشين وأكتوبر والمعادي وحلوان وحدائق الأهرام والسالم والشيخ زايد والرحاب وأبو زعبل والبدرشين والعياط والحوامدية وكرداسة والمرج والبراجيل وأبو النمرس وسرايات والمنيب وصفط اللبن ونكلا': [
    { name: 'التجمع', price: 80 },
    { name: 'القطامية', price: 80 },
    { name: 'الخصوص', price: 80 },
    { name: 'بدرشين', price: 80 },
    { name: 'أكتوبر', price: 80 },
    { name: 'المعادي', price: 80 },
    { name: 'حلوان', price: 80 },
    { name: 'حدائق الأهرام', price: 80 },
    { name: 'السالم', price: 80 },
    { name: 'الشيخ زايد', price: 80 },
    { name: 'الرحاب', price: 80 },
    { name: 'أبو زعبل', price: 80 },
    { name: 'البدرشين', price: 80 },
    { name: 'العياط', price: 80 },
    { name: 'الحوامدية', price: 80 },
    { name: 'كرداسة', price: 80 },
    { name: 'المرج', price: 80 },
    { name: 'البراجيل', price: 80 },
    { name: 'أبو النمرس', price: 80 },
    { name: 'سرايات', price: 80 },
    { name: 'المنيب', price: 80 },
    { name: 'صفط اللبن', price: 80 },
    { name: 'نكلا', price: 80 }
  ],
  'العبور ومدينتي والشروق وبدر والعاشر من رمضان والعياط والصف وأطفيح وطنطا والمنصورة الجديدة والمنصورة': [
    { name: 'العبور', price: 85 },
    { name: 'مدينتي', price: 85 },
    { name: 'الشروق', price: 85 },
    { name: 'بدر', price: 85 },
    { name: 'العاشر من رمضان', price: 85 },
    { name: 'العياط', price: 85 },
    { name: 'الصف', price: 85 },
    { name: 'أطفيح', price: 85 },
    { name: 'طنطا', price: 85 },
    { name: 'المنصورة الجديدة', price: 85 },
    { name: 'المنصورة', price: 85 }
  ],
  'الإسكندرية': [
    { name: 'الإسكندرية', price: 90 },
    { name: 'سيدي جابر', price: 90 },
    { name: 'العجمي', price: 90 },
    { name: 'محرم بك', price: 90 },
    { name: 'المنتزه', price: 90 },
    { name: 'الجمرك', price: 90 },
    { name: 'الرمل', price: 90 },
    { name: 'برج العرب', price: 90 },
    { name: 'العامرية', price: 90 },
    { name: 'المعمورة', price: 90 },
    { name: 'اللبان', price: 90 },
    { name: 'المنشية', price: 90 },
    { name: 'العطارين', price: 90 },
    { name: 'باكوس', price: 90 },
    { name: 'سموحة', price: 90 },
    { name: 'فيكتوريا', price: 90 },
    { name: 'سان ستيفانو', price: 90 },
    { name: 'جليم', price: 90 },
    { name: 'الشاطبي', price: 90 },
    { name: 'كامب شيزار', price: 90 },
    { name: 'زيزينيا', price: 90 },
    { name: 'بولكلي', price: 90 },
    { name: 'لوران', price: 90 },
    { name: 'سيدي بشر', price: 90 },
    { name: 'ميامي', price: 90 },
    { name: 'العصافرة', price: 90 },
    { name: 'المندرة', price: 90 },
    { name: 'أبو قير', price: 90 },
    { name: 'الأنفوشي', price: 90 },
    { name: 'الدخيلة', price: 90 },
    { name: 'الورديان', price: 90 },
    { name: 'القباري', price: 90 },
    { name: 'الناصرية', price: 90 }
  ],
  'الإسماعيلية': [
    { name: 'الإسماعيلية', price: 90 },
    { name: 'فايد', price: 90 },
    { name: 'القنطرة شرق', price: 90 },
    { name: 'القنطرة غرب', price: 90 },
    { name: 'التل الكبير', price: 90 },
    { name: 'أبو صوير', price: 90 },
    { name: 'القصاصين الجديدة', price: 90 }
  ],
  'السويس': [
    { name: 'السويس', price: 90 },
    { name: 'عتاقة', price: 90 },
    { name: 'الجناين', price: 90 },
    { name: 'الأربعين', price: 90 },
    { name: 'فيصل', price: 90 },
    { name: 'العين السخنة', price: 90 }
  ],
  'بورسعيد': [
    { name: 'بورسعيد', price: 90 },
    { name: 'بورفؤاد', price: 90 },
    { name: 'الزهور', price: 90 },
    { name: 'الضواحي', price: 90 },
    { name: 'العرب', price: 90 },
    { name: 'المناخ', price: 90 },
    { name: 'الشرق', price: 90 },
    { name: 'جنوب بورسعيد', price: 90 }
  ],
  'الدقهلية': [
    { name: 'الدقهلية', price: 95 },
    { name: 'طلخا', price: 95 },
    { name: 'ميت غمر', price: 95 },
    { name: 'منية النصر', price: 95 },
    { name: 'دكرنس', price: 95 },
    { name: 'بلقاس', price: 95 },
    { name: 'شربين', price: 95 },
    { name: 'السنبلاوين', price: 95 },
    { name: 'الجمالية', price: 95 },
    { name: 'المطرية', price: 95 },
    { name: 'تمي الأمديد', price: 95 },
    { name: 'أجا', price: 95 },
    { name: 'بني عبيد', price: 95 },
    { name: 'نبروه', price: 95 },
    { name: 'محلة دمنة', price: 95 }
  ],
  'الغربية': [
    { name: 'الغربية', price: 95 },
    { name: 'المحلة الكبرى', price: 95 },
    { name: 'كفر الزيات', price: 95 },
    { name: 'زفتى', price: 95 },
    { name: 'السنطة', price: 95 },
    { name: 'بسيون', price: 95 },
    { name: 'سمنود', price: 95 },
    { name: 'قطور', price: 95 }
  ],
  'الشرقية': [
    { name: 'الشرقية', price: 95 },
    { name: 'الزقازيق', price: 95 },
    { name: 'منيا القمح', price: 95 },
    { name: 'بلبيس', price: 95 },
    { name: 'أبو كبير', price: 95 },
    { name: 'فاقوس', price: 95 },
    { name: 'أبو حماد', price: 95 },
    { name: 'ههيا', price: 95 },
    { name: 'الإبراهيمية', price: 95 },
    { name: 'ديرب نجم', price: 95 },
    { name: 'مشتول السوق', price: 95 },
    { name: 'القنايات', price: 95 },
    { name: 'أولاد صقر', price: 95 },
    { name: 'كفر صقر', price: 95 },
    { name: 'الصالحية الجديدة', price: 95 },
    { name: 'القرين', price: 95 },
    { name: 'الحسينية', price: 95 },
    { name: 'صان الحجر', price: 95 },
    { name: 'العصايد', price: 95 }
  ],
  'دمياط': [
    { name: 'دمياط', price: 95 },
    { name: 'دمياط الجديدة', price: 95 },
    { name: 'رأس البر', price: 95 },
    { name: 'فارسكور', price: 95 },
    { name: 'الزرقا', price: 95 },
    { name: 'كفر سعد', price: 95 }
  ],
  'كفر الشيخ': [
    { name: 'كفر الشيخ', price: 95 },
    { name: 'دسوق', price: 95 },
    { name: 'فوه', price: 95 },
    { name: 'مطوبس', price: 95 },
    { name: 'سيدي سالم', price: 95 },
    { name: 'قلين', price: 95 },
    { name: 'الحامول', price: 95 },
    { name: 'بلطيم', price: 95 },
    { name: 'الرياض', price: 95 },
    { name: 'بيلا', price: 95 },
    { name: 'برج البرلس', price: 95 }
  ],
  'البحيرة': [
    { name: 'البحيرة', price: 95 },
    { name: 'دمنهور', price: 95 },
    { name: 'كفر الدوار', price: 95 },
    { name: 'إيتاي البارود', price: 95 },
    { name: 'أبو حمص', price: 95 },
    { name: 'الدلنجات', price: 95 },
    { name: 'المحمودية', price: 95 },
    { name: 'الرحمانية', price: 95 },
    { name: 'شبراخيت', price: 95 },
    { name: 'حوش عيسى', price: 95 },
    { name: 'إدكو', price: 95 },
    { name: 'رشيد', price: 95 },
    { name: 'النوبارية', price: 95 },
    { name: 'وادي النطرون', price: 95 },
    { name: 'كوم حمادة', price: 95 },
    { name: 'أبو المطامير', price: 95 },
    { name: 'التحرير', price: 95 }
  ],
  'المنوفية': [
    { name: 'المنوفية', price: 95 },
    { name: 'شبين الكوم', price: 95 },
    { name: 'منوف', price: 95 },
    { name: 'سرس الليان', price: 95 },
    { name: 'أشمون', price: 95 },
    { name: 'الباجور', price: 95 },
    { name: 'بركة السبع', price: 95 },
    { name: 'تلا', price: 95 },
    { name: 'الشهداء', price: 95 },
    { name: 'قويسنا', price: 95 },
    { name: 'السادات', price: 95 }
  ],
  'الفيوم': [
    { name: 'الفيوم', price: 105 },
    { name: 'سنورس', price: 105 },
    { name: 'إطسا', price: 105 },
    { name: 'إبشواي', price: 105 },
    { name: 'يوسف الصديق', price: 105 },
    { name: 'طامية', price: 105 },
    { name: 'الحادقة', price: 105 },
    { name: 'الجامعة', price: 105 },
    { name: 'دار الرماد', price: 105 },
    { name: 'العدوة', price: 105 },
    { name: 'الناصرية', price: 105 },
    { name: 'قحافة', price: 105 },
    { name: 'منشأة عبد الله', price: 105 },
    { name: 'دمشقين', price: 105 },
    { name: 'اللاهون', price: 105 },
    { name: 'هوارة المقطع', price: 105 },
    { name: 'هوارة عدلان', price: 105 },
    { name: 'الشيخ فضل', price: 105 },
    { name: 'الروبيات', price: 105 },
    { name: 'الفيوم الجديدة', price: 105 }
  ],
  'بني سويف': [
    { name: 'بني سويف', price: 105 },
    { name: 'الواسطى', price: 105 },
    { name: 'ناصر', price: 105 },
    { name: 'إهناسيا', price: 105 },
    { name: 'ببا', price: 105 },
    { name: 'سمسطا', price: 105 },
    { name: 'الفشن', price: 105 },
    { name: 'بني سويف الجديدة', price: 105 }
  ],
  'أسيوط': [
    { name: 'أسيوط', price: 105 },
    { name: 'ديروط', price: 105 },
    { name: 'منفلوط', price: 105 },
    { name: 'القوصية', price: 105 },
    { name: 'أبنوب', price: 105 },
    { name: 'أبو تيج', price: 105 },
    { name: 'الغنايم', price: 105 },
    { name: 'ساحل سليم', price: 105 },
    { name: 'البداري', price: 105 },
    { name: 'صدفا', price: 105 },
    { name: 'أسيوط الجديدة', price: 105 }
  ],
  'سوهاج': [
    { name: 'سوهاج', price: 105 },
    { name: 'أخميم', price: 105 },
    { name: 'البلينا', price: 105 },
    { name: 'المراغة', price: 105 },
    { name: 'المنشأة', price: 105 },
    { name: 'دار السلام', price: 105 },
    { name: 'جرجا', price: 105 },
    { name: 'جهينة', price: 105 },
    { name: 'ساقلتة', price: 105 },
    { name: 'طما', price: 105 },
    { name: 'طهطا', price: 105 },
    { name: 'العسيرات', price: 105 },
    { name: 'سوهاج الجديدة', price: 105 }
  ],
  'قنا': [
    { name: 'قنا', price: 105 },
    { name: 'أبو تشت', price: 105 },
    { name: 'نجع حمادي', price: 105 },
    { name: 'دشنا', price: 105 },
    { name: 'الوقف', price: 105 },
    { name: 'قفط', price: 105 },
    { name: 'قوص', price: 105 },
    { name: 'نقادة', price: 105 },
    { name: 'فرشوط', price: 105 },
    { name: 'قنا الجديدة', price: 105 }
  ],
  'الأقصر': [
    { name: 'الأقصر', price: 105 },
    { name: 'الزينية', price: 105 },
    { name: 'البياضية', price: 105 },
    { name: 'القرنة', price: 105 },
    { name: 'أرمنت', price: 105 },
    { name: 'الطود', price: 105 },
    { name: 'إسنا', price: 105 },
    { name: 'الأقصر الجديدة', price: 105 }
  ],
  'أسوان': [
    { name: 'أسوان', price: 105 },
    { name: 'دراو', price: 105 },
    { name: 'كوم أمبو', price: 105 },
    { name: 'نصر النوبة', price: 105 },
    { name: 'كلابشة', price: 105 },
    { name: 'إدفو', price: 105 },
    { name: 'أبو سمبل السياحية', price: 105 },
    { name: 'أسوان الجديدة', price: 105 }
  ],
  'النبابة': [
    { name: 'النبابة', price: 105 }
  ],
  'مرسى مطروح والساحل الشمالي والعلمين وسيدي عبد الرحمن ومدينة الحمام': [
    { name: 'مرسى مطروح', price: 115 },
    { name: 'الساحل الشمالي', price: 115 },
    { name: 'العلمين', price: 115 },
    { name: 'سيدي عبد الرحمن', price: 115 },
    { name: 'مدينة الحمام', price: 115 },
    { name: 'الضبعة', price: 115 },
    { name: 'النجيلة', price: 115 },
    { name: 'سيدي براني', price: 115 },
    { name: 'السلوم', price: 115 },
    { name: 'رأس الحكمة', price: 115 }
  ],
  'شرم الشيخ': [
    { name: 'شرم الشيخ', price: 130 }
  ],
  'سفاجا والقصير ورأس غارب ومرسى علم وخليج مكادي والغردقة والطور وجنوب سيناء': [
    { name: 'سفاجا', price: 135 },
    { name: 'القصير', price: 135 },
    { name: 'رأس غارب', price: 135 },
    { name: 'مرسى علم', price: 135 },
    { name: 'خليج مكادي', price: 135 },
    { name: 'الغردقة', price: 135 },
    { name: 'الطور', price: 135 },
    { name: 'طور سيناء', price: 135 },
    { name: 'دهب', price: 135 },
    { name: 'نويبع', price: 135 },
    { name: 'طابا', price: 135 },
    { name: 'سانت كاترين', price: 135 },
    { name: 'أبو رديس', price: 135 },
    { name: 'أبو زنيمة', price: 135 },
    { name: 'رأس سدر', price: 135 },
    { name: 'الشلاتين', price: 135 },
    { name: 'حلايب', price: 135 },
    { name: 'برنيس', price: 135 }
  ]
}; 